[[task]]
  id = "install"
  type = "short"
  cmd = "cat tools.go | grep _ | awk -F'\"' '{print $2}' | xargs -tI % go install %"

[[task]]
  id = "test"
  type = "short"
  cmd = "go test ./..."

[[task]]
  id = "test-integration"
  type = "short"
  dependencies = ["minio"]
  cmd = "go test ./store/s3 -integration"
  env = { AWS_REGION = "us-east-1", AWS_ACCESS_KEY = "minioadmin", AWS_SECRET_KEY = "minioadmin", LFSB_S3_ENDPOINT="http://127.0.0.1:9000" }

[[task]]
  id = "minio"
  type = "long"
  cmd = "minio server ./data/minio"
