[[task]]
  id = "install"
  type = "short"
  cmd = "cat tools.go | grep _ | awk -F'\"' '{print $2}' | xargs -tI % go install %"

[[task]]
  id = "server"
  type = "long"
  cmd = "go run cmd/litefs-backup/*"
  watch = ["**/*.go"]

[[task]]
  id = "test"
  type = "short"
  cmd = "go test ./..."

[[task]]
  id = "test-integration"
  type = "short"
  dependencies = ["minio"]
  cmd = "go test ./store/s3 -integration"

  env = { AWS_REGION = "us-east-1", AWS_ACCESS_KEY = "minioadmin", AWS_SECRET_KEY = "minioadmin", AWS_ENDPOINT_URL_S3="http://127.0.0.1:9000" }

[[task]]
  id = "minio"
  type = "long"
  cmd = """
    mc alias set minio http://127.0.0.1:9000
    mc mb data/minio/lfsb-integration-test
    minio server ./data/minio
  """
